### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by phit** [robotbrain/ForgeTheSane#2]
is this a windows issue? looks like problems with \ and \/
```
D:\temp\ForgeTheSane>python3 main.py ./files/forge-1.13.2-25.0.193-installer.jar
Download https://launcher.mojang.com/v1/objects/30bfe37a8db404db11c7edf02cb5165817afb4d9/client.jar
Download https://files.minecraftforge.net/maven/com/github/jponge/lzma-java/1.3/lzma-java-1.3.jar
Download https://files.minecraftforge.net/maven/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
Download https://libraries.minecraft.net/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
Download https://files.minecraftforge.net/maven/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
Download https://files.minecraftforge.net/maven/com/google/guava/guava/20.0/guava-20.0.jar
Download https://files.minecraftforge.net/maven/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar
Download https://files.minecraftforge.net/maven/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
Download https://files.minecraftforge.net/maven/com/nothome/javaxdelta/2.0.1/javaxdelta-2.0.1.jar
Download https://libraries.minecraft.net/commons-io/commons-io/2.4/commons-io-2.4.jar
Download https://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_config/1.13.2-20190213.203750/mcp_config-1.13.2-20190213.203750.zip
Download https://files.minecraftforge.net/maven/net/md-5/SpecialSource/1.8.3/SpecialSource-1.8.3.jar
Download https://files.minecraftforge.net/maven/net/minecraftforge/binarypatcher/1.0.5/binarypatcher-1.0.5.jar
Extract maven\net/minecraftforge/forge/1.13.2-25.0.193/forge-1.13.2-25.0.193-universal.jar
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    procs = data_setup.data_setup(forge_name)
  File "D:\temp\ForgeTheSane\data_setup.py", line 15, in data_setup
    libs = mvn.get_libraries(install_profile, forge_archive, base)
  File "D:\temp\ForgeTheSane\mvn.py", line 43, in get_libraries
    with archive.open(entry_path) as entry:
  File "C:\Python\Python36\lib\zipfile.py", line 1352, in open
    zinfo = self.getinfo(name)
  File "C:\Python\Python36\lib\zipfile.py", line 1281, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'maven\\\\net/minecraftforge/forge/1.13.2-25.0.193/forge-1.13.2-25.0.193-universal.jar' in the archive"
```

**Comment by phit** [comment]
https://github.com/robotbrain/ForgeTheSane/blob/535315226880ca040be73eb4e4a7f956eba862f8/mvn.py#L41
okay changed that line to `entry_path = 'maven/' + artifact['path']`
since we are in a zip file we dont need OS dependent separators there

---
then i was stuck at this

```
Extract data/client.lzma
Run data\1.13.2-forge-25.0.193\net/minecraftforge/installertools/1.0.3/installertools-1.0.3.jar
Error: Could not find or load main class net.minecraftforge.installertools.ConsoleTool
Process completed with exit code 1
Run data\1.13.2-forge-25.0.193\net/minecraftforge/jarsplitter/1.1.0/jarsplitter-1.1.0.jar
Error: Could not find or load main class net.minecraftforge.jarsplitter.ConsoleTool
Process completed with exit code 1
Run data\1.13.2-forge-25.0.193\net/minecraftforge/installertools/1.0.3/installertools-1.0.3.jar
Error: Could not find or load main class net.minecraftforge.installertools.ConsoleTool
Process completed with exit code 1
Run data\1.13.2-forge-25.0.193\net/md-5/SpecialSource/1.8.3/SpecialSource-1.8.3.jar
Error: Could not find or load main class net.md_5.specialsource.SpecialSource
Process completed with exit code 1
Run data\1.13.2-forge-25.0.193\net/minecraftforge/binarypatcher/1.0.5/binarypatcher-1.0.5.jar
Error: Could not find or load main class net.minecraftforge.binarypatcher.ConsoleTool
Process completed with exit code 1
```

https://github.com/robotbrain/ForgeTheSane/blob/f4d43368909882188786c767dbadc7cc22b6227b/procedures.py#L12

needs to be `';'.join([proc['jar'], *proc['classpath']]),`
i guess that was just a typo, `:` should have never worked
